// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VocabSRS.DAL.Context;

#nullable disable

namespace VocabSRS.DAL.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    partial class SqlServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VocabSRS.Core.Entities.KnownWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatesAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WordId")
                        .IsUnique();

                    b.ToTable("KnownWords");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.Phrase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhraseText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudiedWordId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatesAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudiedWordId");

                    b.ToTable("Phrases");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.PhraseMeaning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhraseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatesAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PhraseId");

                    b.ToTable("PhraseMeanings");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.PhraseSentence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PhraseMeaningId")
                        .HasColumnType("int");

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatesAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PhraseMeaningId");

                    b.ToTable("PhraseSentences");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.StudiedWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoxNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatesAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WordId")
                        .IsUnique();

                    b.ToTable("StudiedWords");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.TypeOfMeaning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TypeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatesAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TypeOfMeanings");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatesAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WordText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.WordMeaning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudiedWordId")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfMeaningId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatesAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudiedWordId");

                    b.HasIndex("TypeOfMeaningId");

                    b.ToTable("WordMeanings");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.WordSentence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatesAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WordMeaningId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WordMeaningId");

                    b.ToTable("WordSentences");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.KnownWord", b =>
                {
                    b.HasOne("VocabSRS.Core.Entities.Word", "Word")
                        .WithOne("KnownWord")
                        .HasForeignKey("VocabSRS.Core.Entities.KnownWord", "WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.Phrase", b =>
                {
                    b.HasOne("VocabSRS.Core.Entities.StudiedWord", "StudiedWord")
                        .WithMany("Phrases")
                        .HasForeignKey("StudiedWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudiedWord");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.PhraseMeaning", b =>
                {
                    b.HasOne("VocabSRS.Core.Entities.Phrase", "Phrase")
                        .WithMany("PhraseMeanings")
                        .HasForeignKey("PhraseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phrase");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.PhraseSentence", b =>
                {
                    b.HasOne("VocabSRS.Core.Entities.PhraseMeaning", "PhraseMeaning")
                        .WithMany("PhraseSentences")
                        .HasForeignKey("PhraseMeaningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhraseMeaning");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.StudiedWord", b =>
                {
                    b.HasOne("VocabSRS.Core.Entities.Word", "Word")
                        .WithOne("StudiedWord")
                        .HasForeignKey("VocabSRS.Core.Entities.StudiedWord", "WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.WordMeaning", b =>
                {
                    b.HasOne("VocabSRS.Core.Entities.StudiedWord", "StudiedWord")
                        .WithMany("WordMeanings")
                        .HasForeignKey("StudiedWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VocabSRS.Core.Entities.TypeOfMeaning", "TypeOfMeaning")
                        .WithMany("WordMeanings")
                        .HasForeignKey("TypeOfMeaningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudiedWord");

                    b.Navigation("TypeOfMeaning");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.WordSentence", b =>
                {
                    b.HasOne("VocabSRS.Core.Entities.WordMeaning", "WordMeaning")
                        .WithMany("WordSentences")
                        .HasForeignKey("WordMeaningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WordMeaning");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.Phrase", b =>
                {
                    b.Navigation("PhraseMeanings");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.PhraseMeaning", b =>
                {
                    b.Navigation("PhraseSentences");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.StudiedWord", b =>
                {
                    b.Navigation("Phrases");

                    b.Navigation("WordMeanings");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.TypeOfMeaning", b =>
                {
                    b.Navigation("WordMeanings");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.Word", b =>
                {
                    b.Navigation("KnownWord");

                    b.Navigation("StudiedWord");
                });

            modelBuilder.Entity("VocabSRS.Core.Entities.WordMeaning", b =>
                {
                    b.Navigation("WordSentences");
                });
#pragma warning restore 612, 618
        }
    }
}
